services:

  ddclient:
    build:
      context: .
      args:
        - ALPINE_VERSION=${ALPINE_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - ./ddclient.conf:/etc/ddclient/ddclient.conf
